application: strom-transparent 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /power
  script: strom-transparent.application
- url: /cron
  script: strom-transparent.application
